# Generated by Django 3.1.5 on 2021-01-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20210124_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': '对象', 'verbose_name_plural': '对象'},
        ),
        migrations.AlterModelOptions(
            name='targettype',
            options={'verbose_name': '对象类型', 'verbose_name_plural': '对象类型'},
        ),
        migrations.AlterModelOptions(
            name='websitelink',
            options={'verbose_name': '站点链接', 'verbose_name_plural': '站点链接'},
        ),
        migrations.AlterModelOptions(
            name='websitetype',
            options={'verbose_name': '站点类型', 'verbose_name_plural': '站点类型'},
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.targettype'),
        ),
    ]
