# Generated by Django 3.1.5 on 2021-04-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_auto_20210417_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelink',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.websitetype'),
        ),
    ]
