# Generated by Django 3.1.5 on 2021-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20210417_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetype',
            name='format_template',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
